import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://rukminim2.flixcart.com/image/612/612/kv8fbm80/t-shirt/g/c/t/xl-13126998-roadster-original-imag86bgfxbrbvy6.jpeg?q=70",
    title: "Women Printed T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹499",
    newPrice: "299",
    company: "ZWERLON",
    color: "Blue",
    category: "Topwear",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/kevpwnk0-0/t-shirt/y/y/y/m-11697294-roadster-original-imafvggewfus88cr.jpeg?q=70",
    title: "Women Solid T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹499",
    newPrice: "199",
    company: "Aahwan",
    color: "Red",
    category: "Topwear",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/kjhgzgw0-0/t-shirt/m/y/y/xs-12193826-roadster-original-imafzfb8pfrz4hhs.jpeg?q=70",
    title: "Women Graphic T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹799",
    newPrice: "199",
    company: "Roadster",
    color: "Pink",
    category: "Topwear",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/kpwybgw0/t-shirt/a/d/8/xl-13321610-roadster-original-imag4fd2tue6swze.jpeg?q=70",
    title: "Women Solid T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹699",
    newPrice: "399",
    company: "Roadster",
    color: "Red",
    category: "Topwear",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/kdt50nk0-0/t-shirt/w/o/f/s-11296054-roadster-original-imafumqyn2ngcdha.jpeg?q=70",
    title: "Women Solid T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹699",
    newPrice: "299",
    company: "Roadster",
    color: "black",
    category: "Topwear",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/jw6pifk0/t-shirt/y/a/d/xl-2439138-roadster-original-imafgwhxkghhyduy.jpeg?q=70",
    title: "Women Solid T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹699",
    newPrice: "299",
    company: "ZWERLON",
    color: "black",
    category: "Topwear",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/kobspe80/t-shirt/t/z/s/xs-1753417-roadster-original-imag2tbhypu9hymj.jpeg?q=70",
    title: "Women Self  T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹490",
    newPrice: "199",
    company: "Aahwan",
    color: "Red",
    category: "Topwear",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/o/7/k/xs-23363982-roadster-original-imagtsc4q7qznkdr.jpeg?q=70",
    title: "Women Printed T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1200",
    newPrice: "399",
    company: "ZWERLON",
    color: "black",
    category: "Topwear",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/kmuxevk0/t-shirt/m/4/y/xs-12193790-roadster-original-imagfnuwjfgxxkam.jpeg?q=70",
    title: "Women soild T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹640",
    newPrice: "199",
    company: "Roadster",
    color: "Pink",
    category: "Topwear",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/e/y/n/s-701-zwerlon-original-imaguht4rsdh2sgb.jpeg?q=70",
    title: "Women A-line Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1099",
    newPrice: "299",
    company: "ZWERLON",
    color: "Red",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/kpzt7680/t-shirt/c/d/6/xs-13126876-roadster-original-imag43n8x8aykgmm.jpeg?q=70",
    title: "Women Prined T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹640",
    newPrice: "299",
    company: "ZWERLON",
    color: "Pink",
    category: "Topwear",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/kjhgzgw0-0/t-shirt/v/g/3/s-12193446-roadster-original-imafzfb93sr2vnrw.jpeg?q=70",
    title: "Women Printed T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹599",
    newPrice: "199",
    company: "Aahwan",
    color: "Blue",
    category: "Topwear",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/d/5/e/s-701-zwerlon-original-imagugtbdyhen2qn.jpeg?q=70",
    title: "Women A-line  Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1099",
    newPrice: "299",
    company: "Roadwear",
    color: "Pink",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/y/x/w/s-aa-00191-pink-aayu-original-imagmmhqz2gthb8v.jpeg?q=70",
    title: "Women Fit Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1099",
    newPrice: "499",
    company: "ZWERLON",
    color: "Pink",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/g/k/7/m-1628-sheetal-associates-original-imagm77fgcjyfjb5.jpeg?q=70",
    title: "Women Bodycon Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1999",
    newPrice: "399",
    company: "Aahwan",
    color: "Blue",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/t/1/n/xl-1624-sheetal-associates-original-imagm77fxqjvefz8.jpeg?q=70",
    title: "Women Bodycon Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1999",
    newPrice: "399",
    company: "Roadster",
    color: "Pink",
    category: "Dresses",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/f/p/m/m-2frock-159-160-hiva-trendz-original-imag3qdfeqv3qhmz-bb.jpeg?q=70",
    title: "Women Flare Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1099",
    newPrice: "399",
    company: "ZWERLON",
    color: "Blue",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/5/t/b/xs-194-black-aahwan-original-imaghyeac2qev33t.jpeg?q=70",
    title: "Women A-line Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1099",
    newPrice: "299",
    company: "ZWERLON",
    color: "black",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/l/s/n/l-ankita-gown-fashion2wear-original-imagh8fyhrghvf53.jpeg?q=70",
    title: "Women Gown Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1099",
    newPrice: "399",
    company: "Aahwan",
    color: "Blue",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/jean/e/t/t/-original-imagq58hgkmmqdbv.jpeg?q=70",
    title: "Women Regular Jeans",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹3999",
    newPrice: "1999",
    company: "LEVI'S",
    color: "Blue",
    category: "Jeans",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/e/a/p/s-pwd322-purshottam-wala-original-imagm6ywr7vz95sz.jpeg?q=70",
    title: "Women Gown Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1099",
    newPrice: "399",
    company: "Roadster",
    color: "Blue",
    category: "Dresses",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/3/x/u/s-e1621-alanta-original-imagf95zesgzk6rz.jpeg?q=70",
    title: "Women Bodycon Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1099",
    newPrice: "399",
    company: "Roadster",
    color: "black",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/x/r/v/28-a7092-0002-levis-original-imagq3c37fayuge9.jpeg?q=70",
    title: " Women Reaguler Jeans",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹2999",
    newPrice: "509",
    company: "LEVI'S",
    color: "black",
    category: "Jeans",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/e/a/4/m-238aroon-aahwan-original-imagskpf6kt2vfmh.jpeg?q=70",
    title: "Women Skater Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1899",
    newPrice: "599",
    company: "Roadster",
    color: "Red",
    category: "Dresses",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/e/d/w/30-21306-0510-levi-s-original-imag75stuxmxdhn5-bb.jpeg?q=70",
    title: "710 Women Skinny Jeans",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹3999",
    newPrice: "1999",
    company: "LEVI'S",
    color: "black",
    category: "Jeans",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/x/b/e/m-194-maroon-aahwan-original-imaghyeaedzghbcx.jpeg?q=70",
    title: "Women A-line Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1299",
    newPrice: "599",
    company: "ZWERLON",
    color: "Red",
    category: "Dresses",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/l4rd0280/jean/a/d/g/36-gtladiesjeans101-guti-original-imagfkyguxa97zgp.jpeg?q=70",
    title: "Women Flared Jeans",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹2999",
    newPrice: "1999",
    company: "LEVI'S",
    color: "black",
    category: "Jeans",
  },
  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/m/c/b/l-170-red-aahwan-original-imagab7fjuuffumr-bb.jpeg?q=70",
    title: "Women Flare Dress",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1999",
    newPrice: "599",
    company: "Aahwan",
    color: "Red",
    category: "Dresses",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/m/6/g/28-21325-0297-levi-s-original-imaghepq7ghhmsp6.jpeg?q=70",
    title: "710 Women Skinny Jeans",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹3999",
    newPrice: "1999",
    company: "LEVI'S",
    color: "Blue",
    category: "Jeans",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/l/8/q/28-a7088-0015-levis-original-imagshzcfmmksgct.jpeg?q=70",
    title: " Women Skinny Jeans",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1999",
    newPrice: "599",
    company: "LEVI'S",
    color: "Blue",
    category: "Jeans",
  },

  {
    img: "https://rukminim2.flixcart.com/image/832/832/l4rd0280/jean/v/9/w/34-gtladiesjeans100-guti-original-imagfkygvexvfzmw.jpeg?q=70",
    title: "Women Flared Jeans",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "1999",
    newPrice: "₹399",
    company: "LEVI'S",
    color: "white",
    category: "Jeans",
  },
];
export default data;
